### ISSUE TITLE
Cheat option not working

### ISSUE THREAD

**Issue by KenRiehle** [Cephas369/BasicOverhaul#1]
I check the box to disable the cheat menu and the cheat menu will still come up when you press U. How can I stop this from happening. Is the option there just for show and not really an option? If that is the case how can I change the keybind key to something I wouldn't use say F12 or the - on the numlock keypad. Thank you for looking into this.

**Comment by Cephas369** [comment]
I've added a option for this now at the end of the config menu to change the key.
